apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  labels:
{{ toYaml .Values.metadata.labels.service | indent 4}}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{ end }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
{{ toYaml .Values.metadata.labels.selector | indent 4 }}
