--- 
- name: zeta-install
  hosts: 35.232.220.174
  remote_user: aprvh4
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: pip is installed
      yum: 
        name: python3-pip,python2-pip
        state: present
    - name: Install docker python package
      pip:
        name: docker
    
    - name: deploy nginx container
      docker_container:
        image: nginx:stable
        name: nginx
        state: started
        log_driver: json-file
        log_options: {"max-size": "100m", "max-file": "3"}
        auto_remove: true
        ports:
          - "8080:80"
    
    - name: configuring logrotate (static config)
      copy:
        src: docker-container
        dest: /etc/logrotate.d/
        owner: root
        group: root
        mode: 0644